### ISSUE TITLE
Listing services for invalid teams creates a PagerDuty connection with an empty token

### ISSUE THREAD

**Issue by nilium** [nilium/lita-interrupt#5]
Relevant exception below:

```
WARN: Exception occurred RuntimeError: Can't parse times of NilClass: :
…/pager_duty-connection-1.0.0/lib/pager_duty/connection.rb:123:in `parse'
…/faraday-0.9.2/lib/faraday/response.rb:16:in `on_complete'
…/faraday-0.9.2/lib/faraday/response.rb:9:in `block in call'
…/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
…/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
…/faraday_middleware-0.9.2/lib/faraday_middleware/request/encode_json.rb:23:in `call'
…/pager_duty-connection-1.0.0/lib/pager_duty/connection.rb:74:in `call'
…/pager_duty-connection-1.0.0/lib/pager_duty/connection.rb:54:in `call'
…/pager_duty-connection-1.0.0/lib/pager_duty/connection.rb:25:in `call'
…/pager_duty-connection-1.0.0/lib/pager_duty/connection.rb:36:in `call'
…/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
…/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
…/pager_duty-connection-1.0.0/lib/pager_duty/connection.rb:205:in `run_request'
…/pager_duty-connection-1.0.0/lib/pager_duty/connection.rb:184:in `get'
…/lita-interrupt-0.1.0/lib/lita/handlers/interrupt.rb:200:in `list_team_services'
…/lita-interrupt-0.1.0/lib/lita/handlers/interrupt.rb:167:in `list_services'
. . .
```

This only happens when passing a team that would not appear for `int team ls` (e.g., `int service ls foobar` where `foobar` is not a team). Not sure yet if this is a bug in lita-interrupt itself or a result of the PagerDuty API returning something unexpected to pager_duty-connection.

Relevant lines for debugging:

- https://github.com/nilium/lita-interrupt/blob/v0.1.0/lib/lita/handlers/interrupt.rb#L200
- https://github.com/technicalpickles/pager_duty-connection/blob/master/lib/pager_duty/connection.rb#L123

**Comment by nilium** [comment]
Narrowed this down to being an issue with the https://github.com/nilium/lita-interrupt/blob/master/lib/interrupt_helper/pager_duty.rb#L7 method returning a PagerDuty connection with a nil or otherwise invalid API token. In this case, it'd be passed through as `Token token=""`, so invalid results are to be expected. The correct approach here is to reject bad tokens.
